services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_TOKEN=${JWT_TOKEN}
    volumes:
      - .:/app